services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    expose:
      - "11434"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  api:
    build: .
    restart: unless-stopped
    environment:
      # Production database configuration
      - DATABASE_URL=postgresql://pbbdbuser:Govinda2025%23@host.docker.internal:5432/pure_bhakti_vault
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=pure_bhakti_vault
      - DB_USER=pbbdbuser
      - DB_PASSWORD=Govinda2025#
      - ENVIRONMENT=production
      # Production CORS origins
      - CORS_ORIGINS=https://www.purebhaktibase.com,https://purebhaktibase.com,https://api.purebhaktibase.com,https://app.purebhaktibase.com
      # Ollama configuration
      - OLLAMA_BASE_URL=http://ollama:11434
    expose:
      - "8000"
    volumes:
      - ./app:/app/app:ro
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"   # API on port 8080
      - "8443:443"  # API SSL on port 8443
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf:ro
      - /Users/kamaldivi/pbb-certs/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  ollama_data:
    driver: local

networks:
  default:
    name: purebhakti_shared_network
    external: true