services:
  api:
    build: .
    restart: unless-stopped
    environment:
      # Use your existing database credentials with Docker-compatible host
      - DATABASE_URL=postgresql://pbbdbuser:Govinda2025%23@host.docker.internal:5432/pure_bhakti_vault
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=pure_bhakti_vault
      - DB_USER=pbbdbuser
      - DB_PASSWORD=Govinda2025#
    expose:
      - "8000"
    volumes:
      - ./app:/app/app:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"    # HTTP (redirects to HTTPS)
      - "8443:443"   # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/purebhaktibase.com.crt:/etc/ssl/certs/purebhaktibase.com.crt:ro
      - ./ssl/purebhaktibase.com.key:/etc/ssl/private/purebhaktibase.com.key:ro
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:443/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: purebhakti_shared_network
    external: true